const paesi = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antartide",
  "Antigua e Barbuda",
  "Antille Olandesi",
  "Arabia Saudita",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaigian",
  "Bahamas",
  "Bahrein",
  "Bangladesh",
  "Barbados",
  "Belgio",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bielorussia",
  "Bolivia",
  "Bosnia Erzegovina",
  "Botswana",
  "Brasile",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambogia",
  "Camerun",
  "Canada",
  "Capo Verde",
  "Ciad",
  "Cile",
  "Cina",
  "Cipro",
  "Colombia",
  "Comore",
  "Congo",
  "Corea del Nord",
  "Corea del Sud",
  "Costa Rica",
  "Costa d’Avorio",
  "Croazia",
  "Cuba",
  "Danimarca",
  "Dominica",
  "Ecuador",
  "Egitto",
  "El Salvador",
  "Emirati Arabi Uniti",
  "Eritrea",
  "Estonia",
  "Etiopia",
  "Federazione Russa",
  "Figi",
  "Filippine",
  "Finlandia",
  "Francia",
  "Gabon",
  "Gambia",
  "Georgia",
  "Georgia del Sud e Isole Sandwich del Sud",
  "Germania",
  "Ghana",
  "Giamaica",
  "Giappone",
  "Gibilterra",
  "Gibuti",
  "Giordania",
  "Grecia",
  "Grenada",
  "Groenlandia",
  "Guadalupa",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guiana Francese",
  "Guinea",
  "Guinea Equatoriale",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Irlanda",
  "Islanda",
  "Isola Bouvet",
  "Isola Norfolk",
  "Isola di Christmas",
  "Isola di Man",
  "Isole Aland",
  "Isole Cayman",
  "Isole Cocos",
  "Isole Cook",
  "Isole Falkland",
  "Isole Faroe",
  "Isole Heard ed Isole McDonald",
  "Isole Marianne Settentrionali",
  "Isole Marshall",
  "Isole Minori lontane dagli Stati Uniti",
  "Isole Solomon",
  "Isole Turks e Caicos",
  "Isole Vergini Americane",
  "Isole Vergini Britanniche",
  "Israele",
  "Italia",
  "Jersey",
  "Kazakistan",
  "Kenya",
  "Kirghizistan",
  "Kiribati",
  "Kuwait",
  "Laos",
  "Lesotho",
  "Lettonia",
  "Libano",
  "Liberia",
  "Libia",
  "Liechtenstein",
  "Lituania",
  "Lussemburgo",
  "Madagascar",
  "Malawi",
  "Maldive",
  "Malesia",
  "Mali",
  "Malta",
  "Marocco",
  "Martinica",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Messico",
  "Micronesia",
  "Moldavia",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Mozambico",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norvegia",
  "Nuova Caledonia",
  "Nuova Zelanda",
  "Oman",
  "Paesi Bassi",
  "Pakistan",
  "Palau",
  "Palestina",
  "Panama",
  "Papua Nuova Guinea",
  "Paraguay",
  "Perù",
  "Pitcairn",
  "Polinesia Francese",
  "Polonia",
  "Portogallo",
  "Portorico",
  "Qatar",
  "Regno Unito",
  "Repubblica Ceca",
  "Repubblica Centrafricana",
  "Repubblica Democratica del Congo",
  "Repubblica Dominicana",
  "Repubblica di Macedonia",
  "Romania",
  "Ruanda",
  "Réunion",
  "Sahara Occidentale",
  "Saint Kitts e Nevis",
  "Saint Lucia",
  "Saint Pierre e Miquelon",
  "Saint Vincent e Grenadines",
  "Samoa",
  "Samoa Americane",
  "San Bartolomeo",
  "San Marino",
  "Sant’Elena",
  "Sao Tomé e Príncipe",
  "Senegal",
  "Serbia",
  "Serbia e Montenegro",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Siria",
  "Slovacchia",
  "Slovenia",
  "Somalia",
  "Spagna",
  "Sri Lanka",
  "Stati Uniti",
  "Sudafrica",
  "Sudan",
  "Suriname",
  "Svalbard e Jan Mayen",
  "Svezia",
  "Svizzera",
  "Swaziland",
  "Tagikistan",
  "Tailandia",
  "Taiwan",
  "Tanzania",
  "Territori australi francesi",
  "Territorio Britannico dell’Oceano Indiano",
  "Timor Est",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad e Tobago",
  "Tunisia",
  "Turchia",
  "Turkmenistan",
  "Tuvalu",
  "Ucraina",
  "Uganda",
  "Ungheria",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vaticano",
  "Venezuela",
  "Vietnam",
  "Wallis e Futuna",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

const nazioneSelect = document.getElementById("nazione");
let desiN = "";
for (let i = 0; i < paesi.length; i++) {
  if (paesi[i] == "India") {
  } else {
    desiN += `<option value="${paesi[i]}">${paesi[i]}</option>`;
  }
}

nazioneSelect.innerHTML += desiN;
